name: MDCA # Name of the Catalog Entry
description: |
  Simple MDCA App
version: '0' # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: https://github.com/tcarlander/rancher-catalog.git # A URL related to the catalog entry
