name: MDCA # Name of the Catalog Entry
description: |
  MDCA App# Description of the Catalog Entry
version: 0 # Version of the Catalog to be used
category: Data # Category to be used for searching catalog entries
maintainer: tc # The maintainer of the catalog entry
license: Apache 2 # The license
projectURL: # A URL related to the catalog entry
